/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_nebulas_walletcore_Native */

#ifndef _Included_io_nebulas_walletcore_Native
#define _Included_io_nebulas_walletcore_Native
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    getPublicKeyFromPrivateKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_nebulas_walletcore_Native_getPublicKeyFromPrivateKey
        (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    verifyPrivateKey
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_nebulas_walletcore_Native_verifyPrivateKey
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    verifyPublicKey
 * Signature: ([BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_nebulas_walletcore_Native_verifyPublicKey
        (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    sign
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_nebulas_walletcore_Native_sign
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    verifySign
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_nebulas_walletcore_Native_verifySign
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    sha3256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_nebulas_walletcore_Native_sha3256
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    rmd160
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_nebulas_walletcore_Native_rmd160
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    scrypt
 * Signature: ([BLjava/lang/String;IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_nebulas_walletcore_Native_scrypt
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    base58FromData
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_nebulas_walletcore_Native_base58FromData
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     io_nebulas_walletcore_Native
 * Method:    base58ToData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_nebulas_walletcore_Native_base58ToData
        (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
